# permissions for end users to view baremetalhosts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetalhost-viewer-role
rules:
- apiGroups:
  - hardware.metal3.io
  resources:
  - baremetalhosts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hardware.metal3.io
  resources:
  - baremetalhosts/status
  verbs:
  - get
